# Generated by Django 4.1.5 on 2023-01-23 21:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('number', models.IntegerField(unique=True, verbose_name='appeal number')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 1, 23, 21, 14, 10, 742026, tzinfo=datetime.timezone.utc), verbose_name='created at')),
                ('description', models.CharField(max_length=256, verbose_name='description')),
                ('status', models.IntegerField(choices=[(0, 'new'), (1, 'in progress'), (2, 'done')], default=0, verbose_name='status')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='appeal creator')),
            ],
        ),
    ]
