# Generated by Django 4.1.5 on 2023-01-23 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 22, 11, 29, 863549, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
