# Generated by Django 4.1.5 on 2023-01-23 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_appeal_created_at_alter_appeal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 23, 22, 12, 54, 814115, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
